swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    encryption: 'tls'
#    stream-options:
#        ssl:
#            allow_self_signed : true
#            verify_peer: false
#            verify_peer_name: false
