#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#app_forgot_password_request:
#   path: /reset-password/request
#   controller: App\Controller\ResetPasswordController

#index:
#
#    path: /{vueRouting}
#    controller: App\Controller\IndexController

